version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@7.3.0

jobs:
  build-and-push-image:
    machine:
      image: ubuntu-2004:current
    resource_class: large
    steps:
      - checkout
      - aws-ecr/ecr-login
      - run:
          name: Install docker buildx
          command: |
            mkdir -vp ~/.docker/cli-plugins/
            curl --silent -L --output ~/.docker/cli-plugins/docker-buildx https://github.com/docker/buildx/releases/download/v0.8.2/buildx-v0.8.2.linux-amd64
            chmod a+x ~/.docker/cli-plugins/docker-buildx
            docker buildx version
      - run:
          name: Build for multiple platforms
          command: |
            docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
            docker context create multiarch
            docker buildx create multiarch --name multiarch --driver docker-container --use
            docker buildx inspect --bootstrap
            docker buildx build --push --platform="linux/arm64,linux/amd64" -t 649427798274.dkr.ecr.us-east-1.amazonaws.com/migrate-base:latest .

workflows:
  build-and-push:
    jobs:
      - build-and-push-image:
          context:
            - aws_ecr
            - aws_circleci_credentials
          filters:
            branches:
              only:
                - master
