name: build-and-push-image

on:
  push:
    branches:
      - master

jobs:
  build-and-push-image:
    name: Build and push Docker image to ECR
    runs-on: ubuntu-latest
    continue-on-error: false
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ACCOUNT_ID: "649427798274"
      AWS_REGION: "us-east-1"
      REPO_NAME: "migrate-base"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker buildx build -t $REGISTRY/$REPO_NAME:latest -t $REGISTRY/$REPO_NAME:$GITHUB_SHA --push --platform linux/amd64,linux/arm64 .
